### ISSUE TITLE
GitHub Action - TypeError: Cannot read properties of undefined (reading 'filename')

### ISSUE THREAD

**Issue by nicholaswilde** [tbroadley/spellchecker-cli#94]
I'm trying to run `spellchecker-cli` in a GitHub Action that runs a script in my repo to spellcheck all of my markdown files. After the 5.0.0 update, my GH Action no longer works. Do you have any idea on how I can fix it?

[`spellcheck.yaml`](https://github.com/nicholaswilde/recipes/blob/3f65eddb23877a9c8401f07efacad271ddb69618/.github/workflows/spellcheck.yaml)
```yaml
---
name: spellcheck
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  spellcheck:
    name: spellcheck
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup npm
        uses: actions/setup-node@v3
      - name: Setup spellchecker
        run: npm install --location=global spellchecker-cli
      - run: npm list --global spellchecker-cli
      - name: Run spellcheck
        run: ./scripts/spellcheck.sh
```

[Failed GH Action Output](https://github.com/nicholaswilde/recipes/runs/7424402249?check_suite_focus=true)
```shell
Run ./scripts/spellcheck.sh
  ./scripts/spellcheck.sh
  shell: /usr/bin/bash -e {0}
/usr/local/lib/node_modules/spellchecker-cli/node_modules/app-root-path/lib/resolve.js:111
		appRootPath = path.dirname(requireFunction.main.filename);
		                                                ^
TypeError: Cannot read properties of undefined (reading 'filename')
    at resolve (/usr/local/lib/node_modules/spellchecker-cli/node_modules/app-root-path/lib/resolve.js:111:51)
    at module.exports (/usr/local/lib/node_modules/spellchecker-cli/node_modules/app-root-path/lib/app-root-path.js:6:[2](https://github.com/nicholaswilde/recipes/runs/7424402249?check_suite_focus=true#step:6:2)0)
    at Object.<anonymous> (/usr/local/lib/node_modules/spellchecker-cli/node_modules/app-root-path/index.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:[3](https://github.com/nicholaswilde/recipes/runs/7424402249?check_suite_focus=true#step:6:3)2)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:2[5](https://github.com/nicholaswilde/recipes/runs/7424402249?check_suite_focus=true#step:6:6))
    at async Promise.all (index 0)
Error: Process completed with exit code 1.
```

[Working GH Action Output](https://github.com/nicholaswilde/recipes/runs/7345592539?check_suite_focus=true)
```shell
Run ./scripts/spellcheck.sh
  ./scripts/spellcheck.sh
  shell: /usr/bin/bash -e {0}
Spellchecking [3](https://github.com/nicholaswilde/recipes/runs/7345592539?check_suite_focus=true#step:5:3)[4](https://github.com/nicholaswilde/recipes/runs/7345592539?check_suite_focus=true#step:5:5)[6](https://github.com/nicholaswilde/recipes/runs/7345592539?check_suite_focus=true#step:5:7) files...
./cook/asian/Coconut Curried Vegetables with Rice.cook: no issues found
./cook/asian/Cool and Spicy Noodle Salad.cook: no issues found
./cook/asian/Crispy Peanut Tofu & Cauliflower Rice Stir-Fry.cook: no issues found
./cook/asian/Everyday Chinese Vegetable Stir-Fry.cook: no issues found
./cook/asian/Noodle-Free Pad Thai.cook: no issues found
./cook/beverages/Iced Chai Latte.cook: no issues found
./cook/beverages/Old Irish Coffee.cook: no issues found
./cook/beverages/Olde Tyme Lemonade.cook: no issues found
./cook/breads/Best-Ever Banana Bread.cook: no issues found
./cook/breads/Bread Machine French Bread.cook: no issues found
...
```

[spellcheck.sh](https://github.com/nicholaswilde/recipes/blob/3f65eddb23877a9c8401f07efacad271ddb69618/scripts/spellcheck.sh)
```bash
#!/bin/bash
set -e
set -o pipefail
shopt -s globstar
shopt -s dotglob nullglob

a=$(git rev-parse --show-toplevel)
cd "${a}"
spellchecker -d dictionary.txt -f {"./cook/**/*.cook","./docs/**/*.md"}
```

It works locally on my machine with version `5.0.0`.
```shell
npm list --global spellchecker-cli
/home/linuxbrew/.linuxbrew/lib
└── spellchecker-cli@5.0.0
```
